---
abstract: |
  **Background** The first sentence orients the reader by introducing the broader field in which the particular research is situated.
  
  **Objectives** What is missing in the literature (ie, the specific gap) and why that matters.
  
  **Methods** Describe the novel method or approach that you used to fill the gap or question.
  
  **Results** Executive summary of the results.
  
  **Discussion** Interpret the results to answer the question that was posed at the end of the context section.
editor_options:
  chunk_output_type: inline
---

```{r}
here::i_am("blank.qmd")
```

# Introduction {#sec-intro}

## Background

Explain the scientific background and rationale for the investigation being reported. Progressively more specific paragraphs that culminate in a clear exposition of what is lacking in the literature. The introduction should not contain a broad literature review beyond the motivation of the paper.

## Objectives

The last paragraph compactly summarizes the results, which fill the gap just established and only briefly previews the conclusion of the paper, if at all.

# Methods {#sec-methods}

# Results {#sec-res}

The first results paragraph is special in that it typically summarizes the overall approach to the problem outlined in the introduction, along with any key innovative methods that were developed.

# Discussion {#sec-discussion}

Explain how the results have filled the gap that was identified in the introduction. Describe how the paper advances the field by providing new opportunities.

# Funding

Give the source of funding and the role of the funders for the present study and, if applicable, for the original study on which the present article is based.

# Acknowledgments

{{< pagebreak >}}

# References {.unnumbered}

{{< pagebreak >}}

# Tables {#sec-tabs}

# Figures {#sec-figs}

{{< pagebreak >}}

# Supplemental material {#sec-sm}

## Supplemental tables

## Supplemental figures
